### PR TITLE
register() need to check if the permission is already registered or not.

### PR DESCRIPTION
**Pull request by wysohn**
/dxl reload throw exception

### CODE REVIEW

**Comment by Sataniel98** [comment]
I don't really get why such a check is necessary. The register() method will most likely not get called in any other context but loading the plugin. This bug has already been fixed here:
https://github.com/DRE2N/DungeonsXL/commit/f1de40ef2f7ffeb910aa7ba340b28bf0694a51a8

**Comment by wysohn** [comment]
I left a comment at f1de40e

and please check the sign issue fix as well :P

**Comment by Sataniel98** [comment]
"ohh just realized that there is a separate branch for 0.15

I was looking at 1.14 that's why :/

I'm kind of new to git system"

No problem, but you usually don't put multiple things into one PR. The topic of this PR evolved from a fix for the reload command into a fix for ghost signs - and now, it merges an unfinished dev branch... I'd appreciate it if it was a bit cleaner as I'm not a master with Git, neither :) I'll create a new one

**Comment by Sataniel98** [comment]
See #150

**Pull request closed without merging**
